spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sandsational_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user123}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:user123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

app.security.jwt.secret=${JWT_SECRET:change-this-dev-secret-change-this-dev-secret-123456}
app.security.jwt.expiration-minutes=120